
% % DIARETDB1\train data set
% % - paths where the images to be cropped are stored
% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\DIARETDB1\train\images' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\train\labels' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\train\hemorrhages' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\train\masks' ...    
% };
% % - paths where the images to be cropped will be saved
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\DIARETDB1\train\images' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\train\labels' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\train\hemorrhages' ...    
%     'C:\_diabetic_retinopathy\DIARETDB1\train\masks' ...
% };
% % - masks to be used to crop the images
% maskPaths = 'C:\_diabetic_retinopathy\DIARETDB1\train\masks';

% -------------------------------------------------------------------------

% % DIARETDB1\test data set
% % - paths where the images to be cropped are stored
% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\DIARETDB1\test\images' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\test\labels' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\test\hemorrhages' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\test\masks' ...    
% };
% % - paths where the images to be cropped will be saved
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\DIARETDB1\test\images' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\test\labels' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\test\hemorrhages' ...    
%     'C:\_diabetic_retinopathy\DIARETDB1\test\masks' ...
% };
% % - masks to be used to crop the images
% maskPaths = 'C:\_diabetic_retinopathy\DIARETDB1\test\masks';

% -------------------------------------------------------------------------

% e-ophtha data set
% - paths where the images to be cropped are stored
sourcePaths = { ...
    'C:\_diabetic_retinopathy\e-ophtha\images' ...
    'C:\_diabetic_retinopathy\e-ophtha\labels' ...
    'C:\_diabetic_retinopathy\e-ophtha\masks' ...    
};
% - paths where the images to be cropped will be saved
outputPaths = { ... 
    'C:\_diabetic_retinopathy\e-ophtha\images' ...
    'C:\_diabetic_retinopathy\e-ophtha\labels' ...
    'C:\_diabetic_retinopathy\e-ophtha\masks' ...     
};
% - masks to be used to crop the images
maskPaths = 'C:\_diabetic_retinopathy\e-ophtha\masks';

% -------------------------------------------------------------------------

% % MESSIDOR data set
% % - paths where the images to be cropped are stored
% % - paths where the images to be cropped are stored
% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\MESSIDOR\images' ...
%     'C:\_diabetic_retinopathy\MESSIDOR\masks' ...    
% };
% % - paths where the images to be cropped will be saved
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\MESSIDOR\images' ...
%     'C:\_diabetic_retinopathy\MESSIDOR\masks' ...       
% };
% % - masks to be used to crop the images
% maskPaths = 'C:\_diabetic_retinopathy\MESSIDOR\masks';
