
config_train_cnn_ma_detector;

% Call CNN MA detector
[detector.net, info] = cnn_ma_detector( 'modelType', modelType, ...
                               'datasetName', datasetName, ...
                               'inputDir', inputDir, ...
                               'expDir', expDir, ...
                               'networkType', networkType, ...
                               'augmented', augmented, ...
                               'whitenData', whitenData, ...
                               'contrastNormalization', contrastNormalization, ...
                               'transferLearningDatasetName', transferLearningDatasetName, ...
                               'trainingType', trainingType, ...
                               'typeOfLesion', type_of_lesion, ...
                               'objective', objective, ...
                               'errorFunction', errorFunction, ...
                               'learningOpts', learningOpts);
detector.method = strcat('cnn-', trainingType);
detector.training_type = trainingType;
           
% If the convnet must be saved
if (save_model)
    [datasetTag] = generate_dataset_tag(datasetName);
    
    current_folder = fullfile(inputDir, strcat(type_of_lesion, '-detection-model'), datasetTag, detector.method);
    mkdir(current_folder);
    
    save(fullfile(current_folder, strcat(detector.net.meta.string_parameters, '.mat')), 'detector');
end