
are_labels = true;

sourcePaths = { ...
    'C:\_diabetic_retinopathy\__' ...
};
outputPaths = { ... 
    'C:\_diabetic_retinopathy\__' ...
};
% Relative reduction
scale = 0.740112994;

% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\DIARETDB1\images' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\labels' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\masks' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\hemorrhages' ...
% };
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\DIARETDB1\images' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\labels' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\masks' ...
%     'C:\_diabetic_retinopathy\DIARETDB1\hemorrhages' ...
% };
% % Relative reduction
% scale = 0.740112994;

% sourcePaths = { ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\train\images' ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\train\masks' ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\test\images' ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\test\masks' ...
% };
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\train\images' ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\train\masks' ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\test\images' ...
%     'C:\_diabetic_retinopathy_backup\Kaggle-sub2\test\masks' ...
% };
% scale = 0.808641975;


% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\e-ophtha\images' ...
%     'C:\_diabetic_retinopathy\e-ophtha\masks' ...
%     'C:\_diabetic_retinopathy\e-ophtha\labels' ...
% };
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\e-ophtha\images' ...
%     'C:\_diabetic_retinopathy\e-ophtha\masks' ...
%     'C:\_diabetic_retinopathy\e-ophtha\labels' ...
% };
% scale = 0.963235294;

% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\KAGGLE\images' ...
%     'C:\_diabetic_retinopathy\KAGGLE\masks' ...
% };
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\KAGGLE\images' ...
%     'C:\_diabetic_retinopathy\KAGGLE\masks' ...
% };
% scale = 0.867549669;

% sourcePaths = { ...
%     'C:\_diabetic_retinopathy\0\images' ...
%     'C:\_diabetic_retinopathy\0\masks' ...
% };
% outputPaths = { ... 
%     'C:\_diabetic_retinopathy\0\images' ...
%     'C:\_diabetic_retinopathy\0\masks' ...
% };
% scale = 0.867549669;
